/**
 * Shopping List Backend Service
 * This service provides endpoints for all related interactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ikmarv@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateShoppingListRequest {
    'name': string;
    'description': string;
    'photo': string;
    'amount': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "photo",
            "baseName": "photo",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateShoppingListRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

