/**
 * Shopping List Backend Service
 * This service provides endpoints for all related interactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ikmarv@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Default error object for services. This gives consistent error object that all services may use.
*/
export class ErrorMessageDto {
    /**
    * Error code
    */
    'status'?: string;
    /**
    * Descriptive error message
    */
    'message': string;
    /**
    * Additional data for this error message.
    */
    'data'?: { [key: string]: any; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "{ [key: string]: any; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ErrorMessageDto.attributeTypeMap;
    }

    public constructor() {
    }
}

