/**
 * Shopping List Backend Service
 * This service provides endpoints for all related interactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ikmarv@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Items {
    /**
    * unique identifier
    */
    'id': string;
    /**
    * name of the item
    */
    'name': string;
    'description': string;
    /**
    * picture of the item
    */
    'photo': string;
    'status'?: ItemsStatusEnum;
    'amount': number;
    'createdAt'?: string;
    'updatedAt'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "photo",
            "baseName": "photo",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ItemsStatusEnum",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Items.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ItemsStatusEnum = "PENDING" | "COMPLETED" ;

