/**
 * Shopping List Backend Service
 * This service provides endpoints for all related interactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ikmarv@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ErrorMessageDto } from '../models/ErrorMessageDto';
import { HttpFile } from '../http/http';

/**
* Status data, check additional message field.
*/
export class StatusDto {
    /**
    * Status can be successful or failed, a value of true indicates success.
    */
    'success': boolean;
    /**
    * additional message describing status.
    */
    'message'?: string;
    /**
    * Data associated with the status, this will not always be present
    */
    'data'?: { [key: string]: any; };
    'error'?: ErrorMessageDto;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "ErrorMessageDto",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StatusDto.attributeTypeMap;
    }

    public constructor() {
    }
}

