/**
 * Shopping List Backend Service
 * This service provides endpoints for all related interactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ikmarv@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SuccessMessage {
    /**
    * Returns a true to state that action was successful
    */
    'success'?: boolean;
    /**
    * Message for successful operation
    */
    'message'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SuccessMessage.attributeTypeMap;
    }

    public constructor() {
    }
}

